export const  Data = [
    {
   q: "What is React?",
a: "A JavaScript framework",
b: "A JavaScript library",
c: "A CSS framework",
d: "A HTML template engine",
ans: "A JavaScript library",
    },
    {
q:"What is the primary purpose of the setState method in React?",
a: "To update the component's props",
b: "To update the component's state",
c: "To render the component",
d: "To destroy the component",

ans: "To update the component's state",
    },
    {
q: "What is a Higher-Order Component (HOc: in React?",
a: "A component that wraps another component",
b: "A component that is wrapped by another component",
c: "A component that renders another component",
d: "A component that is rendered by another component",
ans: "A component that wraps another component",
    },
    {
q: "What is the difference between a controlled and uncontrolled component in React?",
a: "Controlled components are stateless, while uncontrolled components are stateful",
b: "Controlled components are stateful, while uncontrolled components are stateless",
c: "Controlled components are rendered by the parent, while uncontrolled components are rendered by themselves",
d: "Controlled components are used for forms, while uncontrolled components are used for displays",
ans: "Controlled components are stateful, while uncontrolled components are stateless",
    },
    {
q: "What is the purpose of the useEffect hook in React?",
a: "To handle side effects in functional components",
b: "To handle state changes in functional components",
c: "To handle props changes in functional components",
d: "To handle context changes in functional components",
ans: "To handle side effects in functional components",
    },
    {
q: "What is the difference between a class component and a functional component in React?",
a: "Class components are stateless, while functional components are stateful",
b: "Class components are stateful, while functional components are stateless",
c: "Class components use a constructor, while functional components use a function",
d: "Class components use a render method, while functional components use a return statement",
ans: "Class components are stateful, while functional components are stateless",
    },
    {
q: "What is the purpose of the useContext hook in React?",
a: "To access context in functional components",
b: "To access state in functional components",
c: "To access props in functional components",
d: "To access refs in functional components",
ans: "To access context in functional components",
    },
    {
q: "What is the difference between a fragment and a container in React?",
a: "A fragment is a container that wraps multiple components",
b: "A fragment is a component that is wrapped by a container",
c: "A fragment is a component that renders multiple components",
d:  "A fragment is a component that is rendered by a container",
ans: "A fragment is a container that wraps multiple components",
    },
    {
q: "What is the purpose of the useReducer hook in React?",
a: "To handle state changes in functional components using a reducer",
b: "To handle side effects in functional components using a reducer",
c: "To handle context changes in functional components using a reducer",
d: "To handle props changes in functional components using a reducer",
ans: "To handle state changes in functional components using a reducer",
    },
    {
q: "What is the difference between a portal and a modal in React?",
a: "A portal is a component that renders a modal",
b: "A portal is a component that is rendered by a modal",
c: "A portal is a component that renders a component outside the DOM hierarchy",
d: "A portal is a component that is rendered outside the DOM hierarchy",
ans: "A portal is a component that renders a component outside the DOM hierarchy",
    },
]